apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-test-config
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        forward . 8.8.8.8
        cache 30
    }
