apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-test-config
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        log
        errors
        hosts {
            8.8.8.8 google.com
            fallthrough
        }
        forward . 8.8.8.8
        cache 30
        health
    }