apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coredns-test
  namespace: kube-system
  labels:
    k8s-app: coredns-test
spec:
  selector:
    matchLabels:
      k8s-app: coredns-test
  template:
    metadata:
      labels:
        k8s-app: coredns-test
    spec:
      containers:
        - name: coredns
          image: coredns/coredns:latest
          args: [ "-conf", "/etc/coredns/Corefile" ]
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
      volumes:
        - name: config-volume
          configMap:
            name: coredns-test-config