apiVersion: networking.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  name: default-ip-pool
spec:
  ranges:
    - subnet: 	10.10.10.1/24
      rangeStart: 10.10.10.169
      rangeEnd: 10.10.10.175
  selector:
    network: default/untaggednetwork
    scope:
      namespace: default