apiVersion: v1
kind: Service
metadata:
  name: coredns-lb
  namespace: kube-system
spec:
  selector:
    k8s-app: coredns-test
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
    - protocol: TCP
      port: 53
      targetPort: 53
  type: LoadBalancer