apiVersion: v1
kind: Service
metadata:
  name: coredns-lb
  namespace: kube-system
spec:
  selector:
    k8s-app: coredns-test
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  type: LoadBalancer
