apiVersion: v1
kind: Service
metadata:
  name: coredns-lb
  namespace: default
  annotations:
    loadbalancer.harvesterhci.io/network: "default/untaggednetwork"
    loadbalancer.harvesterhci.io/project: "c-m-22hz8849/p-bz9cv"
    loadbalancer.harvesterhci.io/namespace: "default"
spec:
  selector:
    k8s-app: coredns-test
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  type: LoadBalancer
